# ---------- Etapa 1: dependencias ----------
FROM node:22-alpine AS deps

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

# ---------- Etapa 2: build ----------
FROM node:22-alpine AS builder

WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# NEXT_PUBLIC_* se hornea en el bundle en tiempo de build: hay que pasarla aquí.
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ARG NEXT_PUBLIC_TOKEN_KEY
ENV NEXT_PUBLIC_TOKEN_KEY=${NEXT_PUBLIC_TOKEN_KEY}
ARG NEXT_PUBLIC_SESSION_FLAG_COOKIE
ENV NEXT_PUBLIC_SESSION_FLAG_COOKIE=${NEXT_PUBLIC_SESSION_FLAG_COOKIE}
ARG NEXT_PUBLIC_REQUEST_TIMEOUT_MS
ENV NEXT_PUBLIC_REQUEST_TIMEOUT_MS=${NEXT_PUBLIC_REQUEST_TIMEOUT_MS}
ARG NEXT_PUBLIC_PAGE_SIZE
ENV NEXT_PUBLIC_PAGE_SIZE=${NEXT_PUBLIC_PAGE_SIZE}
ARG NEXT_PUBLIC_SESSION_MAX_AGE_MINUTES
ENV NEXT_PUBLIC_SESSION_MAX_AGE_MINUTES=${NEXT_PUBLIC_SESSION_MAX_AGE_MINUTES}
ARG NEXT_PUBLIC_MAIL_FROM
ENV NEXT_PUBLIC_MAIL_FROM=${NEXT_PUBLIC_MAIL_FROM}
ARG NEXT_PUBLIC_SOCIAL_GITHUB
ENV NEXT_PUBLIC_SOCIAL_GITHUB=${NEXT_PUBLIC_SOCIAL_GITHUB}
ARG NEXT_PUBLIC_SOCIAL_LINKEDIN
ENV NEXT_PUBLIC_SOCIAL_LINKEDIN=${NEXT_PUBLIC_SOCIAL_LINKEDIN}
ARG NEXT_PUBLIC_SOCIAL_INSTAGRAM
ENV NEXT_PUBLIC_SOCIAL_INSTAGRAM=${NEXT_PUBLIC_SOCIAL_INSTAGRAM}
ARG NEXT_PUBLIC_SOCIAL_X
ENV NEXT_PUBLIC_SOCIAL_X=${NEXT_PUBLIC_SOCIAL_X}
ARG NEXT_PUBLIC_LEGAL_OWNER
ENV NEXT_PUBLIC_LEGAL_OWNER=${NEXT_PUBLIC_LEGAL_OWNER}
ARG NEXT_PUBLIC_LEGAL_COMPANY
ENV NEXT_PUBLIC_LEGAL_COMPANY=${NEXT_PUBLIC_LEGAL_COMPANY}
ARG NEXT_PUBLIC_LEGAL_CONTACT_EMAIL
ENV NEXT_PUBLIC_LEGAL_CONTACT_EMAIL=${NEXT_PUBLIC_LEGAL_CONTACT_EMAIL}
ARG NEXT_PUBLIC_LEGAL_ANPD_REGISTRATION
ENV NEXT_PUBLIC_LEGAL_ANPD_REGISTRATION=${NEXT_PUBLIC_LEGAL_ANPD_REGISTRATION}

ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

# ---------- Etapa 3: runtime ----------
FROM node:22-alpine AS runner

WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Usuario sin privilegios
RUN addgroup -g 1001 -S nodejs \
    && adduser -u 1001 -S nextjs -G nodejs

# Salida standalone: server + solo lo necesario, más estáticos y public
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

CMD ["node", "server.js"]
