declare namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_API_URL: string;
    NEXT_PUBLIC_TOKEN_KEY: string;
    NEXT_PUBLIC_SESSION_FLAG_COOKIE: string;
    NEXT_PUBLIC_REQUEST_TIMEOUT_MS: string;
    NEXT_PUBLIC_PAGE_SIZE: string;
    NEXT_PUBLIC_SESSION_MAX_AGE_MINUTES: string;
    NEXT_PUBLIC_MAIL_FROM: string;
    NEXT_PUBLIC_SOCIAL_GITHUB: string;
    NEXT_PUBLIC_SOCIAL_LINKEDIN: string;
    NEXT_PUBLIC_SOCIAL_INSTAGRAM: string;
    NEXT_PUBLIC_SOCIAL_X: string;
    NEXT_PUBLIC_LEGAL_OWNER: string;
    NEXT_PUBLIC_LEGAL_COMPANY: string;
    NEXT_PUBLIC_LEGAL_CONTACT_EMAIL: string;
    NEXT_PUBLIC_LEGAL_ANPD_REGISTRATION: string;
  }
}
